// SPDX-License-Identifier: AGPL-3.0-only
mod auth;
mod error;
mod memory_hygiene;
mod middleware;
mod openapi;
mod pipeline;
mod prompt;
mod prompt_log;
mod repetition;
mod routes;
mod state;

use std::sync::Arc;

use anyhow::{Context, Result};
use axum::Router;
use utoipa::OpenApi;
use utoipa_axum::router::OpenApiRouter;
use utoipa_scalar::{Scalar, Servable};

use crate::auth::supabase::SupabaseJwtValidator;
use crate::auth::AuthValidator;
use crate::openapi::ApiDoc;
use crate::state::{AppState, ServerConfig};

#[tokio::main]
async fn main() -> Result<()> {
    // Pull `.env` into the process environment if present. Production
    // deployments (Fly.io secrets, Docker run --env, k8s secrets) won't
    // have a file here and dotenv() returns Err — we ignore it and fall
    // through to the real env. Local quickstart `cp .env.example .env`
    // now works without an explicit `set -a; source .env`.
    let _ = dotenvy::dotenv();

    // The workspace pins `tracing-subscriber` without the `env-filter` feature,
    // so we use the plain fmt initialiser. RUST_LOG is honoured via the
    // tracing-log bridge once the subscriber is installed.
    tracing_subscriber::fmt::init();

    // Subcommand dispatch.
    // Usage:
    //   eros-engine                       run the HTTP service (default)
    //   eros-engine serve                 same as above, explicit
    //   eros-engine migrate               apply sqlx migrations and exit
    //                                     (Fly.io release_command)
    //   eros-engine seed-personas <dir>   load every *.toml in <dir> as a
    //                                     persona genome (idempotent on name)
    //   eros-engine backfill-human-insights  project every companion_insights
    //                                     row into engine.human_insights
    //                                     (idempotent UPSERT; manual, never
    //                                     in release_command)
    //   eros-engine print-openapi         dump the OpenAPI spec to stdout and
    //                                     exit (no DB, no env). Used by the
    //                                     CI drift check.
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("migrate") => run_migrations().await,
        Some("seed-personas") => {
            let dir = args
                .next()
                .unwrap_or_else(|| "/etc/eros-engine/personas".to_string());
            run_seed_personas(&dir).await
        }
        Some("backfill-human-insights") => run_backfill_human_insights().await,
        Some("print-openapi") => run_print_openapi(),
        Some("serve") | None => run_server().await,
        Some(other) => {
            eprintln!("unknown subcommand: {other}");
            eprintln!("usage: eros-engine [serve|migrate|seed-personas <dir>|backfill-human-insights|print-openapi]");
            std::process::exit(2);
        }
    }
}

/// Dump the OpenAPI spec generated by utoipa to stdout. Pure compile-time
/// reflection — no DB pool, no env vars, no I/O beyond stdout. The CI
/// `openapi-snapshot` job diffs this against the committed snapshot to
/// catch handlers/types added without `#[utoipa::path]` / `ToSchema`.
fn run_print_openapi() -> Result<()> {
    // expose_affinity_debug=true so the debug routes are always present
    // in the snapshot. The snapshot is the union of every possible route,
    // not the production-deploy subset.
    let (_router, api) = OpenApiRouter::<crate::state::AppState>::with_openapi(ApiDoc::openapi())
        .merge(routes::router_for_openapi(true))
        .split_for_parts();
    let json = api
        .to_pretty_json()
        .context("serialize OpenAPI doc to JSON")?;
    println!("{json}");
    Ok(())
}

/// Read a directory of `*.toml` persona files and insert each into
/// `engine.persona_genomes`. Idempotent: rows are matched by `name`, so
/// re-running won't create duplicate rows — an existing row is updated in
/// place (id stable, content refreshed, FK references preserved).
async fn run_seed_personas(dir: &str) -> Result<()> {
    use serde::Deserialize;

    #[derive(Debug, Deserialize)]
    struct PersonaFile {
        name: String,
        tip_personality: Option<String>,
        system_prompt: String,
        #[serde(default)]
        art_metadata: serde_json::Value,
    }

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;
    let repo = eros_engine_store::persona::PersonaRepo { pool: &pool };

    let entries = std::fs::read_dir(dir).with_context(|| format!("read_dir({dir}) failed"))?;
    let mut inserted = 0u32;
    let mut skipped = 0u32;
    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }
        let text = std::fs::read_to_string(&path).with_context(|| format!("read {path:?}"))?;
        let f: PersonaFile = toml::from_str(&text).with_context(|| format!("parse {path:?}"))?;

        let (id, created) = repo
            .upsert_genome(
                &f.name,
                &f.system_prompt,
                f.tip_personality.as_deref(),
                f.art_metadata,
            )
            .await
            .with_context(|| format!("upsert {}", f.name))?;
        if created {
            tracing::info!(name = %f.name, %id, "persona inserted");
            inserted += 1;
        } else {
            tracing::info!(name = %f.name, %id, "persona refreshed");
            skipped += 1;
        }
    }
    tracing::info!(inserted, skipped, "seed-personas complete");
    Ok(())
}

/// Project every existing `companion_insights` row into `engine.human_insights`.
/// Idempotent (UPSERT), so re-running is safe. Manual maintenance command —
/// deliberately NOT wired into the Fly release_command.
async fn run_backfill_human_insights() -> Result<()> {
    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;
    let human_repo = eros_engine_store::human_insight::HumanInsightRepo { pool: &pool };

    let rows: Vec<(uuid::Uuid, serde_json::Value)> =
        sqlx::query_as("SELECT user_id, insights FROM engine.companion_insights")
            .fetch_all(&pool)
            .await
            .context("load companion_insights for backfill")?;

    let total = rows.len();
    let mut ok = 0u32;
    let mut failed = 0u32;
    for (user_id, insights) in rows {
        match human_repo.project_from_insights(user_id, &insights).await {
            Ok(()) => ok += 1,
            Err(e) => {
                tracing::warn!(%user_id, "backfill projection failed: {e}");
                failed += 1;
            }
        }
    }
    tracing::info!(total, ok, failed, "backfill-human-insights complete");
    Ok(())
}

/// Apply all sqlx migrations and exit. Fly.io invokes this as the
/// release_command before swapping traffic to the new release.
async fn run_migrations() -> Result<()> {
    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;
    tracing::info!("running migrations…");
    sqlx::migrate!("../eros-engine-store/migrations")
        .run(&pool)
        .await
        .context("sqlx migrate run failed")?;
    tracing::info!("migrations applied");
    Ok(())
}

async fn run_server() -> Result<()> {
    let cfg = ServerConfig::from_env();

    if let Some(dir) = cfg.prompt_log_dir.as_ref() {
        if let Err(e) = std::fs::create_dir_all(dir) {
            tracing::warn!(error = %e, dir = %dir.display(),
                "prompt logging: could not create PROMPT_LOG_DIR; writes may fail");
        }
        tracing::info!(dir = %dir.display(),
            "prompt logging ENABLED — writing raw assembled chat prompts to disk (operator-only)");
    }

    let database_url = std::env::var("DATABASE_URL").context("DATABASE_URL is required")?;
    let pool = eros_engine_store::pool::build(&database_url)
        .await
        .context("failed to connect to DATABASE_URL")?;

    let openrouter_key =
        std::env::var("OPENROUTER_API_KEY").context("OPENROUTER_API_KEY is required")?;
    let attribution = eros_engine_llm::openrouter::AppAttribution {
        referer: std::env::var("OPENROUTER_APP_REFERER")
            .ok()
            .filter(|s| !s.is_empty()),
        title: std::env::var("OPENROUTER_APP_TITLE")
            .ok()
            .filter(|s| !s.is_empty()),
        categories: std::env::var("OPENROUTER_APP_CATEGORIES")
            .ok()
            .filter(|s| !s.is_empty()),
    };
    let voyage_key = std::env::var("VOYAGE_API_KEY").context("VOYAGE_API_KEY is required")?;
    if voyage_key.trim().is_empty() {
        // Loud-fail vs gateway's silent-skip. The gateway has a known
        // regression where an empty VOYAGE_API_KEY silently disables
        // embeddings; we refuse to boot rather than carry that footgun.
        anyhow::bail!(
            "VOYAGE_API_KEY is empty — eros-engine refuses to boot rather than silently disable embeddings"
        );
    }
    let voyage = Arc::new(eros_engine_llm::voyage::VoyageClient::new(voyage_key));

    // Auth: prefer JWKS (asymmetric, the post-2025 Supabase default) and
    // fall back to a legacy HS256 shared secret if one is configured. At
    // least one source must be wired or the server boots with a validator
    // that rejects every token (fail-closed).
    //
    // - SUPABASE_JWKS_URL: explicit override.
    // - SUPABASE_URL: derive `${SUPABASE_URL}/auth/v1/.well-known/jwks.json`.
    // - SUPABASE_JWT_SECRET: legacy HS256 shared secret (optional).
    let jwks_url = std::env::var("SUPABASE_JWKS_URL").ok().or_else(|| {
        std::env::var("SUPABASE_URL")
            .ok()
            .map(|u| format!("{}/auth/v1/.well-known/jwks.json", u.trim_end_matches('/')))
    });
    // Resolve+validate the sources before wiring anything: an empty
    // SUPABASE_JWT_SECRET counts as absent, so `SUPABASE_JWT_SECRET=""` with no
    // JWKS source fails fast here instead of booting a validator that silently
    // rejects every request.
    let legacy_secret = resolve_legacy_secret(
        jwks_url.is_some(),
        std::env::var("SUPABASE_JWT_SECRET").ok(),
    )?;

    let mut validator = SupabaseJwtValidator::new();
    if let Some(url) = jwks_url.as_deref() {
        validator = validator
            .with_jwks_url(url)
            .await
            .with_context(|| format!("failed to load Supabase JWKS from {url}"))?;
    }
    if let Some(secret) = legacy_secret {
        validator = validator.with_legacy_secret(secret);
    }
    let auth: Arc<dyn AuthValidator> = Arc::new(validator);

    // model_config: env override > examples/model_config.toml dev default.
    // The committed example is sanitized; the real config is opted into via
    // MODEL_CONFIG_PATH (the docker/Dockerfile.fly image bakes it in for prod).
    let model_config_path =
        std::env::var("MODEL_CONFIG_PATH").unwrap_or_else(|_| "examples/model_config.toml".into());
    let model_config_text = std::fs::read_to_string(&model_config_path)
        .with_context(|| format!("model_config read failed: {model_config_path}"))?;
    let model_config = Arc::new(
        eros_engine_llm::model_config::ModelConfig::from_toml_str(&model_config_text)
            .with_context(|| format!("model_config parse failed: {model_config_path}"))?,
    );

    // Extraction prompts are required ONLY when the task section exists. A
    // missing [tasks.*_extraction] section means that extraction is off — the
    // engine boots and runs without it. A present section with a blank/absent
    // filter_prompt is a misconfiguration we refuse to boot on. Placed in the
    // serve path only (the print-openapi / backfill subcommands return before
    // reaching here).
    if let Err(msg) = model_config.validate_extraction_prompts() {
        anyhow::bail!(msg);
    }

    if let Err(msg) = model_config.validate_voice_model() {
        anyhow::bail!(msg);
    }

    if let Err(msg) = model_config.validate_product_qa_prompt() {
        anyhow::bail!(msg);
    }
    // Hard prerequisite (spec §1.1): product_qa is judge-routed only. With the
    // LLM PDE off the action is unreachable — warn once and stay inert rather
    // than refusing to boot ("此功能不启用").
    if model_config.resolve_product_qa().is_some() && model_config.resolve_pde().is_none() {
        tracing::warn!(
            "model_config: [tasks.chat_product_qa] is configured but the LLM PDE \
             ([tasks.pde_decision].filter_prompt) is disabled — product_qa is inert"
        );
    }

    let output_regex = match model_config.compile_output_regex() {
        Ok(rules) => Arc::new(rules),
        Err(msg) => anyhow::bail!(msg),
    };

    // OpenRouter client is constructed after model_config so we can wire in
    // the global provider exclusion list from [defaults].ignore_providers.
    let openrouter = Arc::new(
        eros_engine_llm::openrouter::OpenRouterClient::new(openrouter_key, attribution)
            .with_ignore_providers(model_config.defaults.ignore_providers.clone()),
    );

    let state = AppState {
        pool,
        auth,
        config: cfg.clone(),
        openrouter,
        voyage,
        model_config,
        output_regex,
        stream_slots: Arc::new(crate::state::StreamSlots::default()),
    };

    // Compose the OpenAPI-aware router. routes::router applies the auth
    // middleware to /comp/* internally; healthz stays public. We seed
    // the spec with `ApiDoc::openapi()` so the title/servers/tags from
    // `openapi.rs` show up at /docs alongside the per-route paths.
    let (open_router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(routes::router(state.clone()))
        .split_for_parts();

    // Spawn the dreaming-lite sweeper alongside the HTTP service. Returns
    // immediately when DREAMING_DISABLED=1 (or tick=0) is set, so unit
    // tests and self-hosters who want only synchronous behaviour can opt out.
    // Cloned because the next line moves `state` into the router.
    tokio::spawn(crate::pipeline::dreaming::sweeper(state.clone()));

    // companion_insights_snapshot sweeper. Returns immediately when
    // SNAPSHOT_DISABLED=1 or the cron expression fails to parse, so the
    // chat path is unaffected by snapshot misconfig.
    tokio::spawn(crate::pipeline::snapshot::sweeper(state.clone()));

    let app: Router = open_router
        .with_state(state)
        .merge(Scalar::with_url("/docs", api))
        .layer(crate::middleware::SseHeadersLayer)
        .layer(tower_http::trace::TraceLayer::new_for_http());

    let listener = tokio::net::TcpListener::bind(&cfg.bind_addr).await?;
    tracing::info!(
        addr = %cfg.bind_addr,
        debug_affinity = cfg.expose_affinity_debug,
        "eros-engine starting"
    );
    axum::serve(listener, app).await?;
    Ok(())
}

/// Validates the configured JWT sources and returns the legacy HS256 secret to
/// wire, if any. A *non-empty* `SUPABASE_JWT_SECRET` is the only thing that
/// counts as the legacy source — an empty one is treated as absent, so the boot
/// guard agrees with what actually gets wired. Returns an error (fail-fast at
/// boot) when neither a JWKS source nor a non-empty legacy secret is present;
/// otherwise the server would boot a validator that rejects every token.
fn resolve_legacy_secret(has_jwks: bool, jwt_secret: Option<String>) -> Result<Option<String>> {
    let legacy_secret = jwt_secret.filter(|s| !s.is_empty());
    if !has_jwks && legacy_secret.is_none() {
        anyhow::bail!(
            "no JWT validation source configured: set SUPABASE_URL (preferred) \
             or SUPABASE_JWKS_URL for asymmetric JWT validation, and/or \
             SUPABASE_JWT_SECRET for the legacy HS256 path"
        );
    }
    Ok(legacy_secret)
}

#[cfg(test)]
mod tests {
    use super::resolve_legacy_secret;
    use eros_engine_llm::model_config::ModelConfig;

    /// The committed example config is the dev/prod boot default; it MUST pass the
    /// extraction boot gate (both sections present with non-blank filter_prompts),
    /// or `main` bails.
    #[test]
    fn shipped_model_config_satisfies_extraction_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        assert!(
            cfg.validate_extraction_prompts().is_ok(),
            "shipped config must pass the extraction boot gate: {:?}",
            cfg.validate_extraction_prompts()
        );
    }

    #[test]
    fn shipped_model_config_satisfies_product_qa_boot_gate() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = eros_engine_llm::model_config::ModelConfig::from_toml_str(text)
            .expect("shipped example parses");
        cfg.validate_product_qa_prompt()
            .expect("shipped example must pass the product_qa boot gate");
    }

    #[test]
    fn example_config_output_regex_compiles() {
        let text = include_str!("../../../examples/model_config.toml");
        let cfg = ModelConfig::from_toml_str(text).expect("examples/model_config.toml parses");
        assert!(
            cfg.compile_output_regex().is_ok(),
            "shipped example output_regex must compile: {:?}",
            cfg.compile_output_regex().err()
        );
    }

    #[test]
    fn no_source_bails() {
        assert!(resolve_legacy_secret(false, None).is_err());
    }

    #[test]
    fn empty_secret_without_jwks_bails() {
        // The regression: a present-but-empty SUPABASE_JWT_SECRET with no JWKS
        // source must fail fast, not boot an all-reject validator.
        assert!(resolve_legacy_secret(false, Some(String::new())).is_err());
    }

    #[test]
    fn jwks_alone_is_enough_and_wires_no_legacy_secret() {
        let secret = resolve_legacy_secret(true, None).expect("jwks source is sufficient");
        assert_eq!(secret, None);
    }

    #[test]
    fn empty_secret_with_jwks_is_ok_but_not_wired() {
        let secret =
            resolve_legacy_secret(true, Some(String::new())).expect("jwks source is sufficient");
        assert_eq!(
            secret, None,
            "empty secret must not be wired as legacy source"
        );
    }

    #[test]
    fn nonempty_secret_alone_is_enough_and_is_returned() {
        let secret = resolve_legacy_secret(false, Some("shh".to_string()))
            .expect("a non-empty legacy secret is a valid source");
        assert_eq!(secret.as_deref(), Some("shh"));
    }
}
